### ISSUE TITLE
Killed OS + SD Card

### ISSUE THREAD

**Issue by danjanjan** [runlevel-4/firefly-iii-automation#4]
Cant recommend.
While installing generated errors and made my file-system read only.
Cant format SD Card anymore.

**Comment by runlevel-4** [comment]
@danjanjan Do you have any logs or anything that can attest to the installation causing the SD card crash?  I can say with full confidence that I have launched the script countless times on my Pi (using an SD card) and other devices, and have never experienced this issue.  Usually an SD card corruption is due to too many writes, an OS/filesystem corruption, or the hardware lock being set.  This script has nothing in it that would cause a filesystem to crash.  It simply runs existing Linux commands to update the OS, install standard LAMP stack, then pull the necessary software down from the repo.
